# Generated by Django 4.2.13 on 2026-05-29 02:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название зоны')),
                ('zone_type', models.CharField(choices=[('standard', 'Стандарт'), ('vip', 'VIP'), ('pro', 'Про-геймер')], default='standard', max_length=20, verbose_name='Тип зоны')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена/час (₽)')),
            ],
            options={
                'verbose_name': 'Зона',
                'verbose_name_plural': 'Зоны',
            },
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='Номер ПК')),
                ('status', models.CharField(choices=[('available', 'Свободен'), ('booked', 'Забронирован'), ('maintenance', 'Обслуживание')], default='available', max_length=20, verbose_name='Статус')),
                ('cpu', models.CharField(blank=True, max_length=100, verbose_name='Процессор')),
                ('gpu', models.CharField(blank=True, max_length=100, verbose_name='Видеокарта')),
                ('ram', models.CharField(blank=True, max_length=50, verbose_name='ОЗУ')),
                ('monitor', models.CharField(blank=True, max_length=100, verbose_name='Монитор')),
                ('image', models.ImageField(blank=True, null=True, upload_to='computers/', verbose_name='Фото')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computers', to='booking.zone', verbose_name='Зона')),
            ],
            options={
                'verbose_name': 'Компьютер',
                'verbose_name_plural': 'Компьютеры',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Начало сеанса')),
                ('end_time', models.DateTimeField(verbose_name='Конец сеанса')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждено'), ('cancelled', 'Отменено'), ('completed', 'Завершено')], default='pending', max_length=20, verbose_name='Статус')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Итого (₽)')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('manager_note', models.TextField(blank=True, verbose_name='Заметка менеджера')),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.computer', verbose_name='Компьютер')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['-created_at'],
            },
        ),
    ]
